[package]
name = "world-wonders-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = { version = "0.7.5", features = ["macros"] }
httpc-test = "0.1.9"
once_cell = "1.19.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.117", features = ["preserve_order"] }
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
strum = "0.26"
strum_macros = "0.26"
rand = "0.8.5"
tower-http = { version = "0.5", features = ["timeout", "trace"] }
chrono = { version = "0.4.34", features = ["serde", "clock"] }
tower_governor = "0.4.2"
thiserror = "1.0.61"

[dev-dependencies]
chrono = "0.4.38"
httpc-test = "0.1.9"
