version: "3"
services:
  api:
    image: rolvapneseth/world-wonders-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Make sure to match the internal port (rhs) to the port specified in `./config/base.toml`
      - "8138:8138"
