version: "3"
services:
  api:
    image: rolvapneseth/world-wonders-api
    privileged: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8138:8138"
