name: Production CI

on:
    workflow_dispatch:

    push:
      branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install stable Rust toolchain
              run: rustup toolchain install stable

            - name: Build + test code
              run: cargo build --verbose && cargo test --verbose

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build + push Docker image
              uses: docker/bake-action@v5
              with:
                  push: true

            - name: Push README to the Docker Hub description
              uses: peter-evans/dockerhub-description@v4
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                repository: rolvapneseth/world-wonders-api
                short-description: ${{ github.event.repository.description }}
                enable-url-completion: true

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Install sshpass
              run: sudo apt-get install sshpass

            - name: Copy docker-compose.yml
              run: sshpass -v -p ${{ secrets.SERVER_PASSWORD }} scp -P 69 -o StrictHostKeyChecking=no docker-compose.yml root@${{ secrets.SERVER_IP }}:/docker/world-wonders-api

            - name: Deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_IP }}
                  port: 69
                  username: root
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      cd /docker/world-wonders-api
                      docker compose pull && docker compose up -d --remove-orphans && docker image prune -f
