name: Production CI

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install stable Rust toolchain
              run: rustup toolchain install stable

            - name: Build + test code
              run: cargo build --verbose && cargo test --verbose

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build + push Docker image
              uses: docker/bake-action@v5
              with:
                  push: true

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Install sshpass
              run: sudo apt-get install sshpass

            - name: Copy docker-compose.yml
              run: sshpass -v -p ${{ secrets.SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no docker-compose.yml root@${{ secrets.SERVER_IP }}:/docker

            - name: Deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: root
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      cd /docker
                      docker-compose down
                      docker-compose pull
                      docker-compose up -d
